name: Build APK
on: push
jobs:
  build:
    # Gamitin natin ang Ubuntu 22.04 dahil stable ito
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # Java 11 ang pinaka-best friend ng Cordova
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Build App
        run: |
          # Gumawa ng Project
          cordova create app com.dugzhak.pinoypool PinoyPool
          
          # Kopyahin ang files
          cp index.html app/www/
          cp config.xml app/
          
          # Pasukin ang folder
          cd app
          
          # Gamitin ang Android 10.1.2 (Ito ang pinaka-stable sa lahat)
          cordova platform add android@10.1.2
          
          # Build na!
          cordova build android --release -- --packageType=apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PinoyPool-APK
          path: app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
