name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g cordova
      - run: cordova create app com.dugzhak.pool PinoyPool
      - run: rm -rf app/www/*
      - run: cp index.html app/www/
      - run: cp config.xml app/
      - run: cd app && cordova platform add android
      - run: cd app && cordova build android --release
      - uses: actions/upload-artifact@v3
        with:
          name: PinoyPool-APK
          path: app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
